[package]
name = "arp-sniff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.120"
pnet = {version = "0.29.0", features = ["pcap"]}
